"""squashed_init

Revision ID: f95f69a5f3c2
Revises: 
Create Date: 2026-04-16 20:29:53.544840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95f69a5f3c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('dashboard_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('digest_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('country_iso2', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('show_context', sa.String(length=255), nullable=True),
    sa.Column('collection_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('latest_source', sa.String(length=255), nullable=True),
    sa.Column('latest_campaign', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_buyer', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brevo_id', sa.String(length=100), nullable=True),
    sa.Column('file_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_state', sa.String(length=100), nullable=True),
    sa.Column('import_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_city', 'leads', ['city'], unique=False)
    op.create_index('ix_leads_country', 'leads', ['country_iso2'], unique=False)
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index('ix_leads_source', 'leads', ['source'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_table('markets',
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country_iso2', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('spent', sa.BigInteger(), nullable=True),
    sa.Column('cpl', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('frequency', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('launch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('city', 'country_iso2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markets')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_source', table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_index('ix_leads_country', table_name='leads')
    op.drop_index('ix_leads_city', table_name='leads')
    op.drop_table('leads')
    op.drop_table('import_logs')
    op.drop_table('digest_recipients')
    op.drop_table('dashboard_permissions')
    # ### end Alembic commands ###
