"""
Справочные данные для нормализации географических названий: города, сокращения, типичные опечатки, 
сопоставление папок с контекстом и списки стоп-слов для очистки имен файлов.
"""

from typing import Dict, Tuple, Optional, Set

KNOWN_CITIES: Dict[str, Tuple[str, Optional[str]]] = {
    'los angeles': ('US', 'CA'), 'la': ('US', 'CA'), 'san francisco': ('US', 'CA'),
    'sf': ('US', 'CA'), 'san diego': ('US', 'CA'), 'san jose': ('US', 'CA'),
    'irvine': ('US', 'CA'), 'anaheim': ('US', 'CA'), 'sacramento': ('US', 'CA'),
    'fresno': ('US', 'CA'), 'oakland': ('US', 'CA'), 'long beach': ('US', 'CA'),
    'bakersfield': ('US', 'CA'), 'santa ana': ('US', 'CA'), 'riverside': ('US', 'CA'),
    'stockton': ('US', 'CA'), 'pasadena': ('US', 'CA'), 'burbank': ('US', 'CA'),
    'glendale': ('US', 'CA'), 'modesto': ('US', 'CA'), 'rancho mirage': ('US', 'CA'),
    'orange county': ('US', 'CA'), 'oc': ('US', 'CA'), 'covina': ('US', 'CA'),
    'palm springs': ('US', 'CA'), 'santa barbara': ('US', 'CA'),
    'santa clarita': ('US', 'CA'), 'san bernardino': ('US', 'CA'),
    'huntington beach': ('US', 'CA'), 'costa mesa': ('US', 'CA'),
    'torrance': ('US', 'CA'), 'fullerton': ('US', 'CA'), 'el monte': ('US', 'CA'),
    'downey': ('US', 'CA'), 'oceanside': ('US', 'CA'), 'garden grove': ('US', 'CA'),
    'ontario': ('US', 'CA'), 'fontana': ('US', 'CA'), 'rancho cucamonga': ('US', 'CA'),
    'santa rosa': ('US', 'CA'), 'elk grove': ('US', 'CA'), 'corona': ('US', 'CA'),
    'pomona': ('US', 'CA'), 'escondido': ('US', 'CA'), 'temecula': ('US', 'CA'),
    'carlsbad': ('US', 'CA'), 'murrieta': ('US', 'CA'), 'menifee': ('US', 'CA'),
    'vista': ('US', 'CA'), 'san marcos': ('US', 'CA'), 'el cajon': ('US', 'CA'),
    'encinitas': ('US', 'CA'), 'la jolla': ('US', 'CA'), 'chula vista': ('US', 'CA'),
    'national city': ('US', 'CA'), 'la mesa': ('US', 'CA'), 'poway': ('US', 'CA'),
    'solana beach': ('US', 'CA'), 'del mar': ('US', 'CA'),
    'new york': ('US', 'NY'), 'nyc': ('US', 'NY'), 'manhattan': ('US', 'NY'),
    'brooklyn': ('US', 'NY'), 'queens': ('US', 'NY'), 'bronx': ('US', 'NY'),
    'staten island': ('US', 'NY'), 'buffalo': ('US', 'NY'), 'rochester': ('US', 'NY'),
    'yonkers': ('US', 'NY'), 'syracuse': ('US', 'NY'), 'albany': ('US', 'NY'),
    'new rochelle': ('US', 'NY'), 'mount vernon': ('US', 'NY'),
    'chicago': ('US', 'IL'), 'aurora': ('US', 'IL'), 'naperville': ('US', 'IL'),
    'joliet': ('US', 'IL'), 'rockford': ('US', 'IL'), 'springfield': ('US', 'IL'),
    'elgin': ('US', 'IL'), 'peoria': ('US', 'IL'),
    'houston': ('US', 'TX'), 'dallas': ('US', 'TX'), 'san antonio': ('US', 'TX'),
    'austin': ('US', 'TX'), 'fort worth': ('US', 'TX'), 'el paso': ('US', 'TX'),
    'arlington': ('US', 'TX'), 'corpus christi': ('US', 'TX'), 'plano': ('US', 'TX'),
    'lubbock': ('US', 'TX'), 'laredo': ('US', 'TX'), 'irving': ('US', 'TX'),
    'amarillo': ('US', 'TX'), 'grand prairie': ('US', 'TX'), 'mckinney': ('US', 'TX'),
    'frisco': ('US', 'TX'), 'midland': ('US', 'TX'),
    'phoenix': ('US', 'AZ'), 'tucson': ('US', 'AZ'), 'mesa': ('US', 'AZ'),
    'scottsdale': ('US', 'AZ'), 'tempe': ('US', 'AZ'), 'chandler': ('US', 'AZ'),
    'glendale az': ('US', 'AZ'), 'gilbert': ('US', 'AZ'), 'peoria az': ('US', 'AZ'),
    'surprise': ('US', 'AZ'), 'goodyear': ('US', 'AZ'),
    'philadelphia': ('US', 'PA'), 'pittsburgh': ('US', 'PA'), 'allentown': ('US', 'PA'),
    'erie': ('US', 'PA'), 'reading': ('US', 'PA'), 'scranton': ('US', 'PA'),
    'denver': ('US', 'CO'), 'colorado springs': ('US', 'CO'), 'aurora co': ('US', 'CO'),
    'lakewood': ('US', 'CO'), 'boulder': ('US', 'CO'), 'fort collins': ('US', 'CO'),
    'las vegas': ('US', 'NV'), 'reno': ('US', 'NV'), 'henderson': ('US', 'NV'),
    'north las vegas': ('US', 'NV'), 'sparks': ('US', 'NV'),
    'seattle': ('US', 'WA'), 'tacoma': ('US', 'WA'), 'spokane': ('US', 'WA'),
    'bellevue': ('US', 'WA'), 'kent': ('US', 'WA'), 'everett': ('US', 'WA'),
    'renton': ('US', 'WA'), 'federal way': ('US', 'WA'),
    'portland': ('US', 'OR'), 'eugene': ('US', 'OR'), 'salem': ('US', 'OR'),
    'beaverton': ('US', 'OR'), 'hillsboro': ('US', 'OR'), 'bend': ('US', 'OR'),
    'miami': ('US', 'FL'), 'orlando': ('US', 'FL'), 'tampa': ('US', 'FL'),
    'jacksonville': ('US', 'FL'), 'fort lauderdale': ('US', 'FL'),
    'ft. lauderdale': ('US', 'FL'), 'ft lauderdale': ('US', 'FL'),
    'st. petersburg': ('US', 'FL'), 'saint petersburg fl': ('US', 'FL'),
    'hialeah': ('US', 'FL'), 'tallahassee': ('US', 'FL'), 'cape coral': ('US', 'FL'),
    'pembroke pines': ('US', 'FL'), 'hollywood fl': ('US', 'FL'),
    'miramar': ('US', 'FL'), 'coral springs': ('US', 'FL'), 'clearwater': ('US', 'FL'),
    'palm bay': ('US', 'FL'), 'west palm beach': ('US', 'FL'),
    'pompano beach': ('US', 'FL'), 'davie': ('US', 'FL'), 'boca raton': ('US', 'FL'),
    'sunrise': ('US', 'FL'), 'plantation': ('US', 'FL'), 'deerfield beach': ('US', 'FL'),
    'sarasota': ('US', 'FL'), 'fort myers': ('US', 'FL'), 'naples fl': ('US', 'FL'),
    'pensacola': ('US', 'FL'), 'gainesville fl': ('US', 'FL'),
    'daytona beach': ('US', 'FL'), 'kissimmee': ('US', 'FL'),
    'charlotte': ('US', 'NC'), 'raleigh': ('US', 'NC'), 'durham': ('US', 'NC'),
    'greensboro': ('US', 'NC'), 'winston-salem': ('US', 'NC'),
    'fayetteville nc': ('US', 'NC'), 'cary': ('US', 'NC'), 'wilmington nc': ('US', 'NC'),
    'high point': ('US', 'NC'), 'asheville': ('US', 'NC'),
    'atlanta': ('US', 'GA'), 'savannah': ('US', 'GA'), 'augusta': ('US', 'GA'),
    'columbus ga': ('US', 'GA'), 'macon': ('US', 'GA'), 'athens ga': ('US', 'GA'),
    'boston': ('US', 'MA'), 'cambridge': ('US', 'MA'), 'worcester': ('US', 'MA'),
    'lowell': ('US', 'MA'), 'brockton': ('US', 'MA'),
    'detroit': ('US', 'MI'), 'grand rapids': ('US', 'MI'), 'ann arbor': ('US', 'MI'),
    'warren': ('US', 'MI'), 'sterling heights': ('US', 'MI'), 'lansing': ('US', 'MI'),
    'flint': ('US', 'MI'), 'dearborn': ('US', 'MI'), 'royal oak': ('US', 'MI'),
    'minneapolis': ('US', 'MN'), 'st. paul': ('US', 'MN'), 'saint paul': ('US', 'MN'),
    'rochester mn': ('US', 'MN'), 'bloomington mn': ('US', 'MN'),
    'nashville': ('US', 'TN'), 'memphis': ('US', 'TN'), 'knoxville': ('US', 'TN'),
    'chattanooga': ('US', 'TN'), 'clarksville': ('US', 'TN'),
    'new orleans': ('US', 'LA'), 'baton rouge': ('US', 'LA'), 'shreveport': ('US', 'LA'),
    'kansas city': ('US', 'MO'), 'st. louis': ('US', 'MO'), 'saint louis': ('US', 'MO'),
    'springfield mo': ('US', 'MO'), 'columbia mo': ('US', 'MO'),
    'indianapolis': ('US', 'IN'), 'fort wayne': ('US', 'IN'), 'south bend': ('US', 'IN'),
    'evansville': ('US', 'IN'),
    'columbus': ('US', 'OH'), 'cleveland': ('US', 'OH'), 'cincinnati': ('US', 'OH'),
    'toledo': ('US', 'OH'), 'akron': ('US', 'OH'), 'dayton': ('US', 'OH'),
    'baltimore': ('US', 'MD'), 'frederick': ('US', 'MD'), 'rockville': ('US', 'MD'),
    'national harbor': ('US', 'MD'),
    'washington': ('US', 'DC'), 'washington dc': ('US', 'DC'), 'washington d.c.': ('US', 'DC'),
    'richmond': ('US', 'VA'), 'virginia beach': ('US', 'VA'), 'norfolk': ('US', 'VA'),
    'chesapeake': ('US', 'VA'), 'arlington va': ('US', 'VA'), 'alexandria va': ('US', 'VA'),
    'roanoke': ('US', 'VA'),
    'milwaukee': ('US', 'WI'), 'madison': ('US', 'WI'), 'green bay': ('US', 'WI'),
    'salt lake city': ('US', 'UT'), 'provo': ('US', 'UT'), 'ogden': ('US', 'UT'),
    'west jordan': ('US', 'UT'),
    'honolulu': ('US', 'HI'), 'anchorage': ('US', 'AK'), 'fairbanks': ('US', 'AK'),
    'omaha': ('US', 'NE'), 'lincoln': ('US', 'NE'),
    'albuquerque': ('US', 'NM'), 'santa fe': ('US', 'NM'), 'las cruces': ('US', 'NM'),
    'oklahoma city': ('US', 'OK'), 'tulsa': ('US', 'OK'), 'norman': ('US', 'OK'),
    'hartford': ('US', 'CT'), 'new haven': ('US', 'CT'), 'stamford': ('US', 'CT'),
    'bridgeport': ('US', 'CT'), 'waterbury': ('US', 'CT'),
    'boise': ('US', 'ID'), 'nampa': ('US', 'ID'), 'meridian id': ('US', 'ID'),
    'des moines': ('US', 'IA'), 'cedar rapids': ('US', 'IA'),
    'louisville': ('US', 'KY'), 'lexington': ('US', 'KY'),
    'charleston sc': ('US', 'SC'), 'columbia sc': ('US', 'SC'),
    'greenville sc': ('US', 'SC'), 'myrtle beach': ('US', 'SC'),
    'birmingham al': ('US', 'AL'), 'huntsville': ('US', 'AL'), 'montgomery al': ('US', 'AL'),
    'mobile': ('US', 'AL'),
    'jackson ms': ('US', 'MS'),
    'little rock': ('US', 'AR'),
    'wichita': ('US', 'KS'), 'kansas city ks': ('US', 'KS'),
    'newark nj': ('US', 'NJ'), 'jersey city': ('US', 'NJ'), 'montclair': ('US', 'NJ'),
    'atlantic city': ('US', 'NJ'), 'paterson': ('US', 'NJ'),
    'providence': ('US', 'RI'),
    'sioux falls': ('US', 'SD'), 'rapid city': ('US', 'SD'),
    'burlington vt': ('US', 'VT'),
    'portland me': ('US', 'ME'),
    'manchester nh': ('US', 'NH'),

    'toronto': ('CA', 'ON'), 'ottawa': ('CA', 'ON'), 'mississauga': ('CA', 'ON'),
    'hamilton': ('CA', 'ON'), 'london ca': ('CA', 'ON'), 'brampton': ('CA', 'ON'),
    'kitchener': ('CA', 'ON'), 'windsor ca': ('CA', 'ON'), 'markham': ('CA', 'ON'),
    'vaughan': ('CA', 'ON'), 'richmond hill': ('CA', 'ON'),
    'montreal': ('CA', 'QC'), 'quebec city': ('CA', 'QC'), 'quebec': ('CA', 'QC'),
    'laval': ('CA', 'QC'), 'gatineau': ('CA', 'QC'), 'sherbrooke': ('CA', 'QC'),
    'vancouver': ('CA', 'BC'), 'victoria ca': ('CA', 'BC'), 'surrey': ('CA', 'BC'),
    'burnaby': ('CA', 'BC'), 'richmond bc': ('CA', 'BC'), 'kelowna': ('CA', 'BC'),
    'kamloops': ('CA', 'BC'),
    'calgary': ('CA', 'AB'), 'edmonton': ('CA', 'AB'), 'red deer': ('CA', 'AB'),
    'lethbridge': ('CA', 'AB'),
    'winnipeg': ('CA', 'MB'), 'halifax': ('CA', 'NS'), 'saskatoon': ('CA', 'SK'),
    'regina': ('CA', 'SK'), 'moncton': ('CA', 'NB'), 'fredericton': ('CA', 'NB'),
    'saint john nb': ('CA', 'NB'), 'charlottetown': ('CA', 'PE'),
    "st. john's": ('CA', 'NL'), 'yellowknife': ('CA', 'NT'),
    'whitehorse': ('CA', 'YT'), 'thunder bay': ('CA', 'ON'),

    'london': ('GB', None), 'manchester': ('GB', None), 'birmingham': ('GB', None),
    'liverpool': ('GB', None), 'leeds': ('GB', None), 'glasgow': ('GB', None),
    'edinburgh': ('GB', None), 'bristol': ('GB', None), 'cardiff': ('GB', None),
    'belfast': ('GB', None), 'nottingham': ('GB', None), 'sheffield': ('GB', None),
    'newcastle': ('GB', None), 'southampton': ('GB', None), 'aberdeen': ('GB', None),
    'cambridge uk': ('GB', None), 'oxford': ('GB', None), 'exeter': ('GB', None),
    'inverness': ('GB', None),

    'sydney': ('AU', 'NSW'), 'melbourne': ('AU', 'VIC'), 'brisbane': ('AU', 'QLD'),
    'adelaide': ('AU', 'SA'), 'perth': ('AU', 'WA'), 'canberra': ('AU', 'ACT'),
    'gold coast': ('AU', 'QLD'), 'darwin': ('AU', 'NT'), 'hobart': ('AU', 'TAS'),
    'cairns': ('AU', 'QLD'), 'townsville': ('AU', 'QLD'), 'newcastle au': ('AU', 'NSW'),
    'wollongong': ('AU', 'NSW'), 'geelong': ('AU', 'VIC'),

    'auckland': ('NZ', None), 'wellington': ('NZ', None), 'christchurch': ('NZ', None),
    'queenstown': ('NZ', None), 'dunedin': ('NZ', None),

    'amsterdam': ('NL', None), 'rotterdam': ('NL', None), 'the hague': ('NL', None),
    'utrecht': ('NL', None), 'eindhoven': ('NL', None), 'groningen': ('NL', None),
    'berlin': ('DE', None), 'hamburg': ('DE', None), 'munich': ('DE', None),
    'cologne': ('DE', None), 'frankfurt': ('DE', None), 'dusseldorf': ('DE', None),
    'stuttgart': ('DE', None), 'dortmund': ('DE', None), 'hanover': ('DE', None),
    'nuremberg': ('DE', None), 'leipzig': ('DE', None), 'dresden': ('DE', None),
    'paris': ('FR', None), 'marseille': ('FR', None), 'lyon': ('FR', None),
    'toulouse': ('FR', None), 'nice': ('FR', None), 'nantes': ('FR', None),
    'strasbourg': ('FR', None), 'bordeaux': ('FR', None),
    'madrid': ('ES', None), 'barcelona': ('ES', None), 'valencia': ('ES', None),
    'seville': ('ES', None), 'bilbao': ('ES', None), 'malaga': ('ES', None),
    'alicante': ('ES', None),
    'rome': ('IT', None), 'milan': ('IT', None), 'naples': ('IT', None),
    'turin': ('IT', None), 'florence': ('IT', None), 'venice': ('IT', None),
    'bologna': ('IT', None), 'genoa': ('IT', None), 'palermo': ('IT', None),
    'catania': ('IT', None), 'bari': ('IT', None), 'verona': ('IT', None),
    'vienna': ('AT', None), 'salzburg': ('AT', None), 'graz': ('AT', None),
    'innsbruck': ('AT', None),
    'zurich': ('CH', None), 'geneva': ('CH', None), 'bern': ('CH', None),
    'basel': ('CH', None),
    'stockholm': ('SE', None), 'gothenburg': ('SE', None), 'malmo': ('SE', None),
    'umea': ('SE', None), 'lulea': ('SE', None),
    'copenhagen': ('DK', None), 'aarhus': ('DK', None), 'odense': ('DK', None),
    'billund': ('DK', None), 'aalborg': ('DK', None),
    'oslo': ('NO', None), 'bergen': ('NO', None), 'stavanger': ('NO', None),
    'trondheim': ('NO', None), 'tromso': ('NO', None),
    'helsinki': ('FI', None), 'tampere': ('FI', None), 'turku': ('FI', None),
    'oulu': ('FI', None), 'rovaniemi': ('FI', None),
    'dublin': ('IE', None), 'cork': ('IE', None), 'galway': ('IE', None),
    'limerick': ('IE', None),
    'lisbon': ('PT', None), 'porto': ('PT', None), 'faro': ('PT', None),
    'funchal': ('PT', None),
    'brussels': ('BE', None), 'antwerp': ('BE', None), 'ghent': ('BE', None),
    'charleroi': ('BE', None),
    'warsaw': ('PL', None), 'krakow': ('PL', None), 'gdansk': ('PL', None),
    'wroclaw': ('PL', None), 'poznan': ('PL', None), 'katowice': ('PL', None),
    'lublin': ('PL', None), 'szczecin': ('PL', None), 'rzeszow': ('PL', None),
    'prague': ('CZ', None), 'brno': ('CZ', None),
    'budapest': ('HU', None), 'debrecen': ('HU', None),
    'bucharest': ('RO', None), 'cluj': ('RO', None), 'cluj-napoca': ('RO', None),
    'timisoara': ('RO', None), 'iasi': ('RO', None), 'sibiu': ('RO', None),
    'athens': ('GR', None), 'thessaloniki': ('GR', None), 'heraklion': ('GR', None),
    'rhodes': ('GR', None), 'corfu': ('GR', None), 'santorini': ('GR', None),
    'mykonos': ('GR', None), 'chania': ('GR', None),
    'istanbul': ('TR', None), 'ankara': ('TR', None), 'izmir': ('TR', None),
    'antalya': ('TR', None), 'bodrum': ('TR', None), 'trabzon': ('TR', None),
    'moscow': ('RU', None), 'saint petersburg': ('RU', None),
    'st petersburg': ('RU', None), 'kazan': ('RU', None),
    'yekaterinburg': ('RU', None), 'novosibirsk': ('RU', None),
    'sochi': ('RU', None),
    'kyiv': ('UA', None), 'kiev': ('UA', None), 'odessa': ('UA', None),
    'kharkiv': ('UA', None), 'lviv': ('UA', None), 'dnipro': ('UA', None),
    'riga': ('LV', None), 'vilnius': ('LT', None), 'kaunas': ('LT', None),
    'tallinn': ('EE', None),
    'belgrade': ('RS', None), 'zagreb': ('HR', None), 'split': ('HR', None),
    'dubrovnik': ('HR', None), 'ljubljana': ('SI', None), 'skopje': ('MK', None),
    'tirana': ('AL', None), 'sofia': ('BG', None), 'varna': ('BG', None),
    'reykjavik': ('IS', None),

    'dubai': ('AE', None), 'abu dhabi': ('AE', None), 'sharjah': ('AE', None),
    'tehran': ('IR', None), 'isfahan': ('IR', None), 'mashhad': ('IR', None),
    'shiraz': ('IR', None), 'tabriz': ('IR', None),
    'tel aviv': ('IL', None), 'jerusalem': ('IL', None), 'haifa': ('IL', None),
    'riyadh': ('SA', None), 'jeddah': ('SA', None), 'mecca': ('SA', None),
    'medina': ('SA', None), 'dammam': ('SA', None),
    'doha': ('QA', None), 'manama': ('BH', None), 'muscat': ('OM', None),
    'kuwait city': ('KW', None),
    'beirut': ('LB', None), 'amman': ('JO', None),
    'cairo': ('EG', None), 'alexandria': ('EG', None), 'hurghada': ('EG', None),
    'sharm el sheikh': ('EG', None),
    'baghdad': ('IQ', None), 'erbil': ('IQ', None),

    'tokyo': ('JP', None), 'osaka': ('JP', None), 'kyoto': ('JP', None),
    'nagoya': ('JP', None), 'sapporo': ('JP', None), 'fukuoka': ('JP', None),
    'seoul': ('KR', None), 'busan': ('KR', None), 'jeju': ('KR', None),
    'beijing': ('CN', None), 'shanghai': ('CN', None), 'guangzhou': ('CN', None),
    'shenzhen': ('CN', None), 'hong kong': ('HK', None), 'chengdu': ('CN', None),
    'singapore': ('SG', None),
    'bangkok': ('TH', None), 'phuket': ('TH', None), 'chiang mai': ('TH', None),
    'kuala lumpur': ('MY', None), 'penang': ('MY', None),
    'jakarta': ('ID', None), 'bali': ('ID', None),
    'mumbai': ('IN', None), 'delhi': ('IN', None), 'new delhi': ('IN', None),
    'bangalore': ('IN', None), 'chennai': ('IN', None), 'kolkata': ('IN', None),
    'hyderabad': ('IN', None), 'pune': ('IN', None), 'ahmedabad': ('IN', None),
    'jaipur': ('IN', None), 'goa': ('IN', None),
    'manila': ('PH', None), 'cebu': ('PH', None), 'davao': ('PH', None),
    'hanoi': ('VN', None), 'ho chi minh city': ('VN', None),
    'phnom penh': ('KH', None), 'siem reap': ('KH', None),
    'colombo': ('LK', None), 'kathmandu': ('NP', None),
    'ulaanbaatar': ('MN', None),
    'taipei': ('TW', None),

    'sao paulo': ('BR', None), 'rio de janeiro': ('BR', None), 'brasilia': ('BR', None),
    'buenos aires': ('AR', None), 'bogota': ('CO', None), 'medellin': ('CO', None),
    'lima': ('PE', None), 'cusco': ('PE', None),
    'santiago': ('CL', None), 'mexico city': ('MX', None), 'cancun': ('MX', None),
    'guadalajara': ('MX', None), 'monterrey': ('MX', None),

    'johannesburg': ('ZA', None), 'cape town': ('ZA', None), 'durban': ('ZA', None),
    'lagos': ('NG', None), 'nairobi': ('KE', None), 'casablanca': ('MA', None),
    'marrakech': ('MA', None), 'addis ababa': ('ET', None), 'accra': ('GH', None),
    'dar es salaam': ('TZ', None),

    'havana': ('CU', None), 'kingston': ('JM', None), 'san juan': ('PR', None),
    'panama city': ('PA', None), 'san jose cr': ('CR', None),
}

AMBIGUOUS_CITIES: Dict[str, Dict[str, Tuple[str, Optional[str]]]] = {
    'london': {'GB': ('London', None), 'CA': ('London', 'ON')},
    'birmingham': {'GB': ('Birmingham', None), 'US': ('Birmingham', 'AL')},
    'cambridge': {'GB': ('Cambridge', None), 'US': ('Cambridge', 'MA')},
    'richmond': {'US': ('Richmond', 'VA'), 'CA': ('Richmond', 'BC')},
    'victoria': {'CA': ('Victoria', 'BC'), 'AU': ('Victoria', 'VIC')},
    'hamilton': {'CA': ('Hamilton', 'ON'), 'NZ': ('Hamilton', None)},
    'manchester': {'GB': ('Manchester', None), 'US': ('Manchester', 'NH')},
    'bristol': {'GB': ('Bristol', None), 'US': ('Bristol', 'TN')},
    'portland': {'US': ('Portland', 'OR')},
    'charleston': {'US': ('Charleston', 'SC')},
    'springfield': {'US': ('Springfield', 'IL')},
    'columbus': {'US': ('Columbus', 'OH')},
    'aurora': {'US': ('Aurora', 'CO')},
    'jacksonville': {'US': ('Jacksonville', 'FL')},
    'odessa': {'UA': ('Odessa', None), 'US': ('Odessa', 'TX')},
    'pasadena': {'US': ('Pasadena', 'CA')},
    'kansas city': {'US': ('Kansas City', 'MO')},
    'newcastle': {'GB': ('Newcastle', None), 'AU': ('Newcastle', 'NSW')},
    'perth': {'AU': ('Perth', 'WA'), 'GB': ('Perth', None)},
    'saint petersburg': {'RU': ('Saint Petersburg', None), 'US': ('Saint Petersburg', 'FL')},
    'st petersburg': {'RU': ('Saint Petersburg', None), 'US': ('Saint Petersburg', 'FL')},
    'arlington': {'US': ('Arlington', 'TX')},
    'huntington': {'US': ('Huntington', 'NY')},
}

CITY_TYPOS: Dict[str, str] = {
    'devner': 'denver', 'denever': 'denver',
    'gothemburg': 'gothenburg', 'goteborg': 'gothenburg', 'göteborg': 'gothenburg',
    'birmhingham': 'birmingham', 'birminham': 'birmingham',
    'ottowa': 'ottawa', 'ottava': 'ottawa',
    'monreal': 'montreal', 'montréal': 'montreal',
    'stockhol': 'stockholm',
    'housten': 'houston', 'huston': 'houston',
    'philidelphia': 'philadelphia', 'philly': 'philadelphia',
    'pittsburg': 'pittsburgh',
    'cincinatti': 'cincinnati', 'cincinati': 'cincinnati',
    'minneaoplis': 'minneapolis',
    'milwuakee': 'milwaukee', 'milwakee': 'milwaukee',
    'clevaland': 'cleveland', 'detriot': 'detroit',
    'atlana': 'atlanta', 'seatle': 'seattle', 'seattel': 'seattle',
    'portand': 'portland', 'sacremento': 'sacramento',
    'albequerque': 'albuquerque', 'albuqerque': 'albuquerque',
    'moskow': 'moscow', 'moskva': 'moscow', 'sidney': 'sydney',
    'melbourn': 'melbourne', 'brisban': 'brisbane',
    'copenhagan': 'copenhagen', 'kobenhavn': 'copenhagen', 'copenhagnen': 'copenhagen',
    'zuerich': 'zurich', 'zürich': 'zurich', 'muenchen': 'munich', 'münchen': 'munich',
    'koeln': 'cologne', 'köln': 'cologne', 'duesseldorf': 'dusseldorf', 'düsseldorf': 'dusseldorf',
    'frankfurk': 'frankfurt', 'umeå': 'umea', 'malmö': 'malmo',
    'ft. lauderdale': 'fort lauderdale', 'ft lauderdale': 'fort lauderdale',
    'ft. lauderadle': 'fort lauderdale', 'ft lauderadle': 'fort lauderdale',
    'lauderdale': 'fort lauderdale', 'st louis': 'saint louis', 'st. louis': 'saint louis',
    'st paul': 'saint paul', 'st. paul': 'saint paul',
    'st. petersburgh': 'saint petersburg', 'st petersburgh': 'saint petersburg',
    'st. john': 'saint john nb', 'st john': 'saint john nb',
    'washingon': 'washington', 'washinton': 'washington',
    'san diago': 'san diego', 'sandiego': 'san diego',
    'san franciso': 'san francisco', 'sanfrancisco': 'san francisco',
    'newyork': 'new york', 'new yourk': 'new york',
    'losangeles': 'los angeles', 'lasvegas': 'las vegas',
    'oklahomacity': 'oklahoma city', 'saltlakecity': 'salt lake city',
    'kansascity': 'kansas city', 'fortworth': 'fort worth',
    'fortlauderdale': 'fort lauderdale', 'sanantonio': 'san antonio',
    'sanjose': 'san jose', 'longbeach': 'long beach',
    'virginiabeach': 'virginia beach', 'coloradosprings': 'colorado springs',
    'grandrapids': 'grand rapids', 'westpalmbeach': 'west palm beach',
    'bocaraton': 'boca raton', 'coralsprings': 'coral springs', 'capecoral': 'cape coral',
}

NOT_CITIES: Set[str] = {
    'europe', 'asia', 'africa', 'oceania', 'americas',
    'middle east', 'north america', 'south america', 'central america',
    'usa', 'us', 'u.s.', 'u.s.a.', 'united states', 'united states of america', 'america',
    'uk', 'u.k.', 'united kingdom', 'great britain', 'england', 'scotland', 'wales',
    'canada', 'australia', 'new zealand', 'iran', 'iraq', 'israel', 'sweden', 'norway',
    'denmark', 'finland', 'germany', 'france', 'italy', 'spain', 'portugal', 'netherlands',
    'belgium', 'switzerland', 'austria', 'poland', 'czech republic', 'czechia',
    'hungary', 'romania', 'greece', 'turkey', 'russia', 'ukraine',
    'brazil', 'mexico', 'argentina', 'colombia', 'peru', 'chile',
    'japan', 'china', 'india', 'south korea', 'thailand', 'malaysia',
    'indonesia', 'philippines', 'vietnam', 'singapore',
    'saudi arabia', 'uae', 'united arab emirates', 'qatar', 'bahrain', 'oman', 'kuwait',
    'egypt', 'south africa', 'nigeria', 'kenya', 'morocco', 'ghana', 'ethiopia',
    'n/a', 'na', 'none', 'null', 'unknown', '-', '--', '---', '.', '..', 'nan',
    'test', 'testing', 'asdf', 'xxx', 'other', 'general', 'various',
    'florida general', 'florida', 'california', 'texas', 'new york state',
}

COUNTRY_ALIASES: Dict[str, str] = {
    'usa': 'US', 'u.s.a.': 'US', 'u.s.': 'US', 'us': 'US', 'united states': 'US', 'america': 'US',
    'uk': 'GB', 'u.k.': 'GB', 'england': 'GB', 'great britain': 'GB', 'united kingdom': 'GB',
    'uae': 'AE', 'united arab emirates': 'AE', 'south korea': 'KR', 'korea': 'KR',
    'czech republic': 'CZ', 'czechia': 'CZ', 'russia': 'RU', 'iran': 'IR',
    'taiwan': 'TW', 'hong kong': 'HK', 'macau': 'MO', 'new zealand': 'NZ',
    'saudi arabia': 'SA', 'south africa': 'ZA', 'australia': 'AU', 'canada': 'CA',
    'germany': 'DE', 'france': 'FR', 'italy': 'IT', 'spain': 'ES', 'portugal': 'PT',
    'sweden': 'SE', 'norway': 'NO', 'denmark': 'DK', 'finland': 'FI', 'ireland': 'IE',
    'belgium': 'BE', 'switzerland': 'CH', 'austria': 'AT', 'poland': 'PL',
    'hungary': 'HU', 'romania': 'RO', 'greece': 'GR', 'turkey': 'TR', 'ukraine': 'UA',
    'japan': 'JP', 'china': 'CN', 'india': 'IN', 'brazil': 'BR', 'mexico': 'MX',
}

FOLDER_TO_CONTEXT: Dict[str, Dict[str, Optional[str]]] = {
    '(1) usa': {'country': 'US', 'region': 'North America'},
    'usa': {'country': 'US', 'region': 'North America'},
    '(2) canada': {'country': 'CA', 'region': 'North America'},
    'canada': {'country': 'CA', 'region': 'North America'},
    '(3) europe': {'country': None, 'region': 'Europe'},
    'europe': {'country': None, 'region': 'Europe'},
    '(4) australia': {'country': 'AU', 'region': 'Oceania'},
    'australia': {'country': 'AU', 'region': 'Oceania'},
    '(5) dubai, middle east, asia': {'country': None, 'region': 'Middle East'},
    'dubai, middle east, asia': {'country': None, 'region': 'Middle East'},
    '(6) industry': {'country': None, 'region': None},
    'industry': {'country': None, 'region': None},
    'total': {'country': None, 'region': None},
    'presales subscribers': {'country': None, 'region': None},
    'mwma audience': {'country': None, 'region': None},
    'master lists': {'country': None, 'region': None},
    'merch buyer contacts': {'country': None, 'region': None},
    'snapchat': {'country': None, 'region': None},
    'mailchimp': {'country': None, 'region': None},
}

FILENAME_NOISE: Set[str] = {
    'presales', 'presale', 'subz', 'subs', 'subscribers', 'subscriber',
    'sheet1', 'sheet', 'list', 'full', 'total', 'master', 'all',
    'january', 'february', 'march', 'april', 'may', 'june',
    'july', 'august', 'september', 'october', 'november', 'december',
    'signup', 'sign', 'up', 'database', 'db', 'site', 'data',
    'export', 'import', 'backup', 'copy', 'final', 'new', 'old',
    'contacts', 'contact', 'mailchimp', 'eventbrite', 'ticketbuyers',
    'ticketing', 'news', 'farsi', 'persian', 'members', 'member',
    'max', 'amini', 'documents', 'master', 'document',
    'notification', 'notifications', 'updated', 'update',
    'show', 'shows', 'english', 'en', 'e', 'f', 'form',
    '2nd', '3rd', '4th', '5th', '1st', 'early', 'sales',
    'patrons', 'patron', 'prime', 'unholy', 'sheep',
    'audience', 'mwma', 'ibt', 'hz', 'got',
}

FILENAME_LANGUAGES: Set[str] = {
    'english', 'farsi', 'persian', 'en', 'arabic', 'french', 'german', 'spanish',
    'turkish', 'russian', 'italian', 'dutch', 'swedish', 'danish', 'norwegian',
    'finnish', 'portuguese', 'polish', 'czech', 'hungarian', 'romanian', 'greek',
}

FOLDER_CITY_OVERRIDES: Dict[str, Tuple[str, str, Optional[str]]] = {
    # США
    'ann arbor': ('Ann Arbor', 'US', 'MI'),
    'atlanta': ('Atlanta', 'US', 'GA'),
    'atlanta': ('Atlanta', 'US', 'GA'),
    'austin': ('Austin', 'US', 'TX'),
    'boston': ('Boston', 'US', 'MA'),
    'covina laugh factory': ('Covina', 'US', 'CA'),
    'chicago': ('Chicago', 'US', 'IL'),
    'columbus': ('Columbus', 'US', 'OH'),
    'connecticut': ('Hartford', 'US', 'CT'),
    'dallas': ('Dallas', 'US', 'TX'),
    'denver': ('Denver', 'US', 'CO'),
    'florida general': ('Miami', 'US', 'FL'),
    'fresno': ('Fresno', 'US', 'CA'),
    'ft lauderadle': ('Fort Lauderdale', 'US', 'FL'),
    'ft. lauderdale': ('Fort Lauderdale', 'US', 'FL'),
    'houston': ('Houston', 'US', 'TX'),
    'huntington': ('Huntington', 'US', 'NY'),
    'idaho': ('Boise', 'US', 'ID'),
    'irvine': ('Irvine', 'US', 'CA'),
    'las vegas': ('Las Vegas', 'US', 'NV'),
    'los angeles': ('Los Angeles', 'US', 'CA'),
    'louisiana': ('New Orleans', 'US', 'LA'),
    'memphis': ('Memphis', 'US', 'TN'),
    'miami': ('Miami', 'US', 'FL'),
    'nashville': ('Nashville', 'US', 'TN'),
    'new york': ('New York', 'US', 'NY'),
    'north carolina': ('Charlotte', 'US', 'NC'),
    'ohio': ('Columbus', 'US', 'OH'),
    'oklahoma': ('Oklahoma City', 'US', 'OK'),
    'orange county': ('Orange County', 'US', 'CA'),
    'orlando': ('Orlando', 'US', 'FL'),
    'pennsylvania': ('Philadelphia', 'US', 'PA'),
    'phoenix az': ('Phoenix', 'US', 'AZ'),
    'portland': ('Portland', 'US', 'OR'),
    'sacramento': ('Sacramento', 'US', 'CA'),
    'san diego': ('San Diego', 'US', 'CA'),
    'san francisco': ('San Francisco', 'US', 'CA'),
    'san francisco & san jose': ('San Francisco', 'US', 'CA'),
    'san jose': ('San Jose', 'US', 'CA'),
    'seattle': ('Seattle', 'US', 'WA'),
    'seattle capitol hill comedy-bar': ('Seattle', 'US', 'WA'),
    'st. louis': ('Saint Louis', 'US', 'MO'),
    'tampa fl': ('Tampa', 'US', 'FL'),
    'tempe az': ('Tempe', 'US', 'AZ'),
    'tennessee': ('Nashville', 'US', 'TN'),
    'washington': ('Washington', 'US', 'DC'),
    'atlantic city': ('Atlantic City', 'US', 'NJ'),
    # Канада
    'calgary': ('Calgary', 'CA', 'AB'),
    'edmonton': ('Edmonton', 'CA', 'AB'),
    'montreal': ('Montreal', 'CA', 'QC'),
    'ottawa': ('Ottawa', 'CA', 'ON'),
    'toronto': ('Toronto', 'CA', 'ON'),
    'vancouver': ('Vancouver', 'CA', 'BC'),
    'winnipeg': ('Winnipeg', 'CA', 'MB'),
    # Европа
    'amsterdam': ('Amsterdam', 'NL', None),
    'athens': ('Athens', 'GR', None),
    'barcelona': ('Barcelona', 'ES', None),
    'berlin': ('Berlin', 'DE', None),
    'birmingham': ('Birmingham', 'GB', None),
    'cologne': ('Cologne', 'DE', None),
    'copenhagen': ('Copenhagen', 'DK', None),
    'dusseldorf': ('Dusseldorf', 'DE', None),
    'düsseldorf': ('Dusseldorf', 'DE', None),
    'frankfurt': ('Frankfurt', 'DE', None),
    'gothenburg': ('Gothenburg', 'SE', None),
    'göteborg': ('Gothenburg', 'SE', None),
    'hamburg': ('Hamburg', 'DE', None),
    'hanover': ('Hanover', 'DE', None),
    'london': ('London', 'GB', None),
    'manchester': ('Manchester', 'GB', None),
    'munich': ('Munich', 'DE', None),
    'rotterdam': ('Rotterdam', 'NL', None),
    'stockholm': ('Stockholm', 'SE', None),
    # Австралия / Океания
    'adelaide': ('Adelaide', 'AU', 'SA'),
    'auckland': ('Auckland', 'NZ', None),
    'brisbane': ('Brisbane', 'AU', 'QLD'),
    'melbourne': ('Melbourne', 'AU', 'VIC'),
    'perth': ('Perth', 'AU', 'WA'),
    'sydney': ('Sydney', 'AU', 'NSW'),
    # Ближний Восток
    'dubai': ('Dubai', 'AE', None),
}
