"""
Справочник IATA-кодов аэропортов, сопоставленных с городами и странами,
а также сокращения штатов США.
"""

IATA_TO_CITY = {
    'ATL': ('Atlanta', 'US'),
    'ANC': ('Anchorage', 'US'),
    'AUS': ('Austin', 'US'),
    'BDL': ('Hartford', 'US'),
    'BHM': ('Birmingham', 'US'),
    'BNA': ('Nashville', 'US'),
    'BOI': ('Boise', 'US'),
    'BOS': ('Boston', 'US'),
    'BUF': ('Buffalo', 'US'),
    'BUR': ('Burbank', 'US'),
    'BWI': ('Baltimore', 'US'),
    'CHS': ('Charleston', 'US'),
    'CLE': ('Cleveland', 'US'),
    'CLT': ('Charlotte', 'US'),
    'CMH': ('Columbus', 'US'),
    'CVG': ('Cincinnati', 'US'),
    'DAL': ('Dallas', 'US'),
    'DCA': ('Washington', 'US'),
    'DEN': ('Denver', 'US'),
    'DFW': ('Dallas', 'US'),
    'DSM': ('Des Moines', 'US'),
    'DTW': ('Detroit', 'US'),
    'ELP': ('El Paso', 'US'),
    'EWR': ('Newark', 'US'),
    'FLL': ('Fort Lauderdale', 'US'),
    'GRR': ('Grand Rapids', 'US'),
    'GSP': ('Greenville', 'US'),
    'HNL': ('Honolulu', 'US'),
    'HOU': ('Houston', 'US'),
    'IAD': ('Washington', 'US'),
    'IAH': ('Houston', 'US'),
    'ICT': ('Wichita', 'US'),
    'IND': ('Indianapolis', 'US'),
    'JAX': ('Jacksonville', 'US'),
    'JFK': ('New York', 'US'),
    'LAS': ('Las Vegas', 'US'),
    'LAX': ('Los Angeles', 'US'),
    'LGA': ('New York', 'US'),
    'LIT': ('Little Rock', 'US'),
    'MCI': ('Kansas City', 'US'),
    'MCO': ('Orlando', 'US'),
    'MDW': ('Chicago', 'US'),
    'MEM': ('Memphis', 'US'),
    'MIA': ('Miami', 'US'),
    'MKE': ('Milwaukee', 'US'),
    'MSN': ('Madison', 'US'),
    'MSP': ('Minneapolis', 'US'),
    'MSY': ('New Orleans', 'US'),
    'OAK': ('Oakland', 'US'),
    'OKC': ('Oklahoma City', 'US'),
    'OMA': ('Omaha', 'US'),
    'ONT': ('Ontario', 'US'),
    'ORD': ('Chicago', 'US'),
    'PBI': ('West Palm Beach', 'US'),
    'PDX': ('Portland', 'US'),
    'PHL': ('Philadelphia', 'US'),
    'PHX': ('Phoenix', 'US'),
    'PIT': ('Pittsburgh', 'US'),
    'PVD': ('Providence', 'US'),
    'RDU': ('Raleigh', 'US'),
    'RIC': ('Richmond', 'US'),
    'RNO': ('Reno', 'US'),
    'RSW': ('Fort Myers', 'US'),
    'SAN': ('San Diego', 'US'),
    'SAT': ('San Antonio', 'US'),
    'SAV': ('Savannah', 'US'),
    'SDF': ('Louisville', 'US'),
    'SEA': ('Seattle', 'US'),
    'SFO': ('San Francisco', 'US'),
    'SJC': ('San Jose', 'US'),
    'SLC': ('Salt Lake City', 'US'),
    'SMF': ('Sacramento', 'US'),
    'SNA': ('Santa Ana', 'US'),
    'SRQ': ('Sarasota', 'US'),
    'STL': ('St. Louis', 'US'),
    'SYR': ('Syracuse', 'US'),
    'TPA': ('Tampa', 'US'),
    'TUL': ('Tulsa', 'US'),
    'TUS': ('Tucson', 'US'),
    'ABQ': ('Albuquerque', 'US'),
    'ALB': ('Albany', 'US'),
    'AMA': ('Amarillo', 'US'),
    'BTV': ('Burlington', 'US'),
    'COS': ('Colorado Springs', 'US'),
    'CRP': ('Corpus Christi', 'US'),
    'DAY': ('Dayton', 'US'),
    'FAT': ('Fresno', 'US'),
    'GEG': ('Spokane', 'US'),
    'GSO': ('Greensboro', 'US'),
    'HSV': ('Huntsville', 'US'),
    'KOA': ('Kona', 'US'),
    'LEX': ('Lexington', 'US'),
    'LBB': ('Lubbock', 'US'),
    'MAF': ('Midland', 'US'),
    'MFR': ('Medford', 'US'),
    'MHT': ('Manchester', 'US'),
    'MOB': ('Mobile', 'US'),
    'MYR': ('Myrtle Beach', 'US'),
    'OGG': ('Kahului', 'US'),
    'PNS': ('Pensacola', 'US'),
    'PSP': ('Palm Springs', 'US'),
    'PWM': ('Portland', 'US'),
    'ROC': ('Rochester', 'US'),
    'SBN': ('South Bend', 'US'),
    'SHV': ('Shreveport', 'US'),
    'TYS': ('Knoxville', 'US'),
    'XNA': ('Fayetteville', 'US'),
    'LIH': ('Lihue', 'US'),
    'EUG': ('Eugene', 'US'),
    'AVL': ('Asheville', 'US'),
    'CAE': ('Columbia', 'US'),
    'CAK': ('Akron', 'US'),
    'CHA': ('Chattanooga', 'US'),
    'FAI': ('Fairbanks', 'US'),
    'FNT': ('Flint', 'US'),
    'FSD': ('Sioux Falls', 'US'),
    'FWA': ('Fort Wayne', 'US'),
    'GNV': ('Gainesville', 'US'),
    'GPT': ('Gulfport', 'US'),
    'ILM': ('Wilmington', 'US'),
    'JAN': ('Jackson', 'US'),
    'LAN': ('Lansing', 'US'),
    'MGM': ('Montgomery', 'US'),
    'MLI': ('Moline', 'US'),
    'RAP': ('Rapid City', 'US'),
    'ROA': ('Roanoke', 'US'),
    'SGF': ('Springfield', 'US'),
    'SWF': ('Newburgh', 'US'),
    'TOL': ('Toledo', 'US'),
    'TRI': ('Bristol', 'US'),
    'VPS': ('Destin', 'US'),

    'YYZ': ('Toronto', 'CA'),
    'YVR': ('Vancouver', 'CA'),
    'YUL': ('Montreal', 'CA'),
    'YYC': ('Calgary', 'CA'),
    'YEG': ('Edmonton', 'CA'),
    'YOW': ('Ottawa', 'CA'),
    'YWG': ('Winnipeg', 'CA'),
    'YHZ': ('Halifax', 'CA'),
    'YQB': ('Quebec City', 'CA'),
    'YXE': ('Saskatoon', 'CA'),
    'YQR': ('Regina', 'CA'),
    'YLW': ('Kelowna', 'CA'),
    'YXU': ('London', 'CA'),
    'YQT': ('Thunder Bay', 'CA'),
    'YKA': ('Kamloops', 'CA'),
    'YYJ': ('Victoria', 'CA'),
    'YQM': ('Moncton', 'CA'),
    'YFC': ('Fredericton', 'CA'),
    'YSJ': ('Saint John', 'CA'),
    'YYG': ('Charlottetown', 'CA'),
    'YDF': ("St. John's", 'CA'),
    'YZF': ('Yellowknife', 'CA'),
    'YXY': ('Whitehorse', 'CA'),

    'LHR': ('London', 'GB'),
    'LGW': ('London', 'GB'),
    'STN': ('London', 'GB'),
    'LTN': ('London', 'GB'),
    'LCY': ('London', 'GB'),
    'MAN': ('Manchester', 'GB'),
    'BHX': ('Birmingham', 'GB'),
    'EDI': ('Edinburgh', 'GB'),
    'GLA': ('Glasgow', 'GB'),
    'BRS': ('Bristol', 'GB'),
    'LPL': ('Liverpool', 'GB'),
    'NCL': ('Newcastle', 'GB'),
    'EMA': ('Nottingham', 'GB'),
    'BFS': ('Belfast', 'GB'),
    'ABZ': ('Aberdeen', 'GB'),
    'CWL': ('Cardiff', 'GB'),
    'LBA': ('Leeds', 'GB'),
    'SOU': ('Southampton', 'GB'),
    'EXT': ('Exeter', 'GB'),
    'INV': ('Inverness', 'GB'),
    'JER': ('Jersey', 'GB'),

    'CDG': ('Paris', 'FR'),
    'ORY': ('Paris', 'FR'),
    'NCE': ('Nice', 'FR'),
    'LYS': ('Lyon', 'FR'),
    'MRS': ('Marseille', 'FR'),
    'TLS': ('Toulouse', 'FR'),
    'BOD': ('Bordeaux', 'FR'),
    'NTE': ('Nantes', 'FR'),
    'SXB': ('Strasbourg', 'FR'),

    'FRA': ('Frankfurt', 'DE'),
    'MUC': ('Munich', 'DE'),
    'BER': ('Berlin', 'DE'),
    'DUS': ('Dusseldorf', 'DE'),
    'HAM': ('Hamburg', 'DE'),
    'CGN': ('Cologne', 'DE'),
    'STR': ('Stuttgart', 'DE'),
    'HAJ': ('Hanover', 'DE'),
    'NUE': ('Nuremberg', 'DE'),
    'LEJ': ('Leipzig', 'DE'),
    'DTM': ('Dortmund', 'DE'),
    'DRS': ('Dresden', 'DE'),

    'AMS': ('Amsterdam', 'NL'),
    'RTM': ('Rotterdam', 'NL'),
    'EIN': ('Eindhoven', 'NL'),

    'MAD': ('Madrid', 'ES'),
    'BCN': ('Barcelona', 'ES'),
    'PMI': ('Palma de Mallorca', 'ES'),
    'AGP': ('Malaga', 'ES'),
    'ALC': ('Alicante', 'ES'),
    'VLC': ('Valencia', 'ES'),
    'SVQ': ('Seville', 'ES'),
    'BIO': ('Bilbao', 'ES'),
    'TFS': ('Tenerife', 'ES'),
    'LPA': ('Las Palmas', 'ES'),
    'IBZ': ('Ibiza', 'ES'),
    'SCQ': ('Santiago de Compostela', 'ES'),

    'FCO': ('Rome', 'IT'),
    'MXP': ('Milan', 'IT'),
    'LIN': ('Milan', 'IT'),
    'VCE': ('Venice', 'IT'),
    'NAP': ('Naples', 'IT'),
    'BLQ': ('Bologna', 'IT'),
    'CTA': ('Catania', 'IT'),
    'PMO': ('Palermo', 'IT'),
    'PSA': ('Pisa', 'IT'),
    'FLR': ('Florence', 'IT'),
    'TRN': ('Turin', 'IT'),
    'BGY': ('Bergamo', 'IT'),
    'BRI': ('Bari', 'IT'),
    'CAG': ('Cagliari', 'IT'),
    'VRN': ('Verona', 'IT'),
    'GOA': ('Genoa', 'IT'),

    'LIS': ('Lisbon', 'PT'),
    'OPO': ('Porto', 'PT'),
    'FAO': ('Faro', 'PT'),
    'FNC': ('Funchal', 'PT'),

    'ATH': ('Athens', 'GR'),
    'SKG': ('Thessaloniki', 'GR'),
    'HER': ('Heraklion', 'GR'),
    'RHO': ('Rhodes', 'GR'),
    'CFU': ('Corfu', 'GR'),
    'CHQ': ('Chania', 'GR'),
    'JTR': ('Santorini', 'GR'),
    'JMK': ('Mykonos', 'GR'),
    'KGS': ('Kos', 'GR'),

    'VIE': ('Vienna', 'AT'),
    'SZG': ('Salzburg', 'AT'),
    'INN': ('Innsbruck', 'AT'),
    'GRZ': ('Graz', 'AT'),

    'ZRH': ('Zurich', 'CH'),
    'GVA': ('Geneva', 'CH'),
    'BSL': ('Basel', 'CH'),
    'BRN': ('Bern', 'CH'),

    'BRU': ('Brussels', 'BE'),
    'CRL': ('Charleroi', 'BE'),
    'ANR': ('Antwerp', 'BE'),

    'CPH': ('Copenhagen', 'DK'),
    'BLL': ('Billund', 'DK'),
    'AAL': ('Aalborg', 'DK'),

    'OSL': ('Oslo', 'NO'),
    'BGO': ('Bergen', 'NO'),
    'TRD': ('Trondheim', 'NO'),
    'SVG': ('Stavanger', 'NO'),
    'TOS': ('Tromso', 'NO'),

    'ARN': ('Stockholm', 'SE'),
    'GOT': ('Gothenburg', 'SE'),
    'MMX': ('Malmo', 'SE'),
    'LLA': ('Lulea', 'SE'),
    'UME': ('Umea', 'SE'),

    'HEL': ('Helsinki', 'FI'),
    'TMP': ('Tampere', 'FI'),
    'TKU': ('Turku', 'FI'),
    'OUL': ('Oulu', 'FI'),
    'RVN': ('Rovaniemi', 'FI'),

    'DUB': ('Dublin', 'IE'),
    'ORK': ('Cork', 'IE'),
    'SNN': ('Shannon', 'IE'),
    'KNO': ('Knock', 'IE'),

    'KEF': ('Reykjavik', 'IS'),

    'WAW': ('Warsaw', 'PL'),
    'KRK': ('Krakow', 'PL'),
    'GDN': ('Gdansk', 'PL'),
    'WRO': ('Wroclaw', 'PL'),
    'POZ': ('Poznan', 'PL'),
    'KTW': ('Katowice', 'PL'),
    'RZE': ('Rzeszow', 'PL'),
    'LUZ': ('Lublin', 'PL'),
    'SZZ': ('Szczecin', 'PL'),

    'PRG': ('Prague', 'CZ'),
    'BRQ': ('Brno', 'CZ'),

    'BUD': ('Budapest', 'HU'),

    'OTP': ('Bucharest', 'RO'),
    'CLJ': ('Cluj-Napoca', 'RO'),
    'TSR': ('Timisoara', 'RO'),
    'IAS': ('Iasi', 'RO'),
    'SBZ': ('Sibiu', 'RO'),

    'SOF': ('Sofia', 'BG'),
    'VAR': ('Varna', 'BG'),
    'BOJ': ('Burgas', 'BG'),

    'ZAG': ('Zagreb', 'HR'),
    'SPU': ('Split', 'HR'),
    'DBV': ('Dubrovnik', 'HR'),

    'BEG': ('Belgrade', 'RS'),
    'NIS': ('Nis', 'RS'),

    'LJU': ('Ljubljana', 'SI'),

    'SKP': ('Skopje', 'MK'),
    'OHD': ('Ohrid', 'MK'),

    'TIA': ('Tirana', 'AL'),

    'RIX': ('Riga', 'LV'),
    'VNO': ('Vilnius', 'LT'),
    'KUN': ('Kaunas', 'LT'),
    'TLL': ('Tallinn', 'EE'),

    'IST': ('Istanbul', 'TR'),
    'SAW': ('Istanbul', 'TR'),
    'ESB': ('Ankara', 'TR'),
    'AYT': ('Antalya', 'TR'),
    'ADB': ('Izmir', 'TR'),
    'DLM': ('Dalaman', 'TR'),
    'BJV': ('Bodrum', 'TR'),
    'TZX': ('Trabzon', 'TR'),
    'GZT': ('Gaziantep', 'TR'),
    'ASR': ('Kayseri', 'TR'),
    'VAN': ('Van', 'TR'),

    'SVO': ('Moscow', 'RU'),
    'DME': ('Moscow', 'RU'),
    'VKO': ('Moscow', 'RU'),
    'LED': ('St. Petersburg', 'RU'),
    'KZN': ('Kazan', 'RU'),
    'SVX': ('Yekaterinburg', 'RU'),
    'OVB': ('Novosibirsk', 'RU'),
    'ROV': ('Rostov-on-Don', 'RU'),
    'KRR': ('Krasnodar', 'RU'),
    'AER': ('Sochi', 'RU'),
    'UFA': ('Ufa', 'RU'),
    'VVO': ('Vladivostok', 'RU'),

    'IEV': ('Kyiv', 'UA'),
    'KBP': ('Kyiv', 'UA'),
    'ODS': ('Odessa', 'UA'),
    'LWO': ('Lviv', 'UA'),
    'HRK': ('Kharkiv', 'UA'),
    'DNK': ('Dnipro', 'UA'),

    'MSQ': ('Minsk', 'BY'),
    'GYD': ('Baku', 'AZ'),
    'TBS': ('Tbilisi', 'GE'),
    'EVN': ('Yerevan', 'AM'),
    'FRU': ('Bishkek', 'KG'),
    'TAS': ('Tashkent', 'UZ'),
    'ALA': ('Almaty', 'KZ'),
    'NQZ': ('Astana', 'KZ'),

    'DXB': ('Dubai', 'AE'),
    'AUH': ('Abu Dhabi', 'AE'),
    'SHJ': ('Sharjah', 'AE'),
    'DOH': ('Doha', 'QA'),
    'BAH': ('Manama', 'BH'),
    'KWI': ('Kuwait City', 'KW'),
    'MCT': ('Muscat', 'OM'),
    'RUH': ('Riyadh', 'SA'),
    'JED': ('Jeddah', 'SA'),
    'DMM': ('Dammam', 'SA'),
    'MED': ('Medina', 'SA'),
    'TLV': ('Tel Aviv', 'IL'),
    'AMM': ('Amman', 'JO'),
    'BEY': ('Beirut', 'LB'),
    'BGW': ('Baghdad', 'IQ'),
    'EBL': ('Erbil', 'IQ'),
    'THR': ('Tehran', 'IR'),
    'IFN': ('Isfahan', 'IR'),
    'MHD': ('Mashhad', 'IR'),

    'CAI': ('Cairo', 'EG'),
    'HRG': ('Hurghada', 'EG'),
    'SSH': ('Sharm El Sheikh', 'EG'),
    'LXR': ('Luxor', 'EG'),
    'ALG': ('Algiers', 'DZ'),
    'ORN': ('Oran', 'DZ'),
    'CMN': ('Casablanca', 'MA'),
    'RAK': ('Marrakech', 'MA'),
    'FEZ': ('Fez', 'MA'),
    'AGA': ('Agadir', 'MA'),
    'TUN': ('Tunis', 'TN'),
    'TIP': ('Tripoli', 'LY'),
    'JNB': ('Johannesburg', 'ZA'),
    'CPT': ('Cape Town', 'ZA'),
    'DUR': ('Durban', 'ZA'),
    'PLZ': ('Port Elizabeth', 'ZA'),
    'NBO': ('Nairobi', 'KE'),
    'MBA': ('Mombasa', 'KE'),
    'ADD': ('Addis Ababa', 'ET'),
    'LOS': ('Lagos', 'NG'),
    'ABV': ('Abuja', 'NG'),
    'ACC': ('Accra', 'GH'),
    'DSS': ('Dakar', 'SN'),
    'ABJ': ('Abidjan', 'CI'),
    'DAR': ('Dar es Salaam', 'TZ'),
    'ZNZ': ('Zanzibar', 'TZ'),
    'EBB': ('Entebbe', 'UG'),
    'KGL': ('Kigali', 'RW'),
    'MRU': ('Mauritius', 'MU'),
    'TNR': ('Antananarivo', 'MG'),
    'MPM': ('Maputo', 'MZ'),
    'LUN': ('Lusaka', 'ZM'),
    'HRE': ('Harare', 'ZW'),
    'WDH': ('Windhoek', 'NA'),
    'GBE': ('Gaborone', 'BW'),

    'DEL': ('New Delhi', 'IN'),
    'BOM': ('Mumbai', 'IN'),
    'BLR': ('Bangalore', 'IN'),
    'MAA': ('Chennai', 'IN'),
    'CCU': ('Kolkata', 'IN'),
    'HYD': ('Hyderabad', 'IN'),
    'COK': ('Kochi', 'IN'),
    'PNQ': ('Pune', 'IN'),
    'AMD': ('Ahmedabad', 'IN'),
    'GOI': ('Goa', 'IN'),
    'JAI': ('Jaipur', 'IN'),
    'TRV': ('Thiruvananthapuram', 'IN'),
    'LKO': ('Lucknow', 'IN'),
    'GAU': ('Guwahati', 'IN'),
    'IXC': ('Chandigarh', 'IN'),
    'VTZ': ('Visakhapatnam', 'IN'),

    'CMB': ('Colombo', 'LK'),
    'KTM': ('Kathmandu', 'NP'),
    'DAC': ('Dhaka', 'BD'),
    'CGP': ('Chittagong', 'BD'),
    'ISB': ('Islamabad', 'PK'),
    'KHI': ('Karachi', 'PK'),
    'LHE': ('Lahore', 'PK'),
    'MLE': ('Male', 'MV'),

    'PEK': ('Beijing', 'CN'),
    'PKX': ('Beijing', 'CN'),
    'PVG': ('Shanghai', 'CN'),
    'SHA': ('Shanghai', 'CN'),
    'CAN': ('Guangzhou', 'CN'),
    'SZX': ('Shenzhen', 'CN'),
    'CTU': ('Chengdu', 'CN'),
    'CKG': ('Chongqing', 'CN'),
    'HGH': ('Hangzhou', 'CN'),
    'XIY': ('Xian', 'CN'),
    'NKG': ('Nanjing', 'CN'),
    'KMG': ('Kunming', 'CN'),
    'WUH': ('Wuhan', 'CN'),
    'TSN': ('Tianjin', 'CN'),
    'CSX': ('Changsha', 'CN'),
    'TAO': ('Qingdao', 'CN'),
    'SYX': ('Sanya', 'CN'),
    'NNG': ('Nanning', 'CN'),
    'DLC': ('Dalian', 'CN'),
    'XMN': ('Xiamen', 'CN'),
    'FOC': ('Fuzhou', 'CN'),
    'HFE': ('Hefei', 'CN'),
    'CGO': ('Zhengzhou', 'CN'),
    'SHE': ('Shenyang', 'CN'),
    'HRB': ('Harbin', 'CN'),
    'URC': ('Urumqi', 'CN'),

    'HKG': ('Hong Kong', 'HK'),
    'MFM': ('Macau', 'MO'),

    'TPE': ('Taipei', 'TW'),
    'KHH': ('Kaohsiung', 'TW'),
    'RMQ': ('Taichung', 'TW'),

    'NRT': ('Tokyo', 'JP'),
    'HND': ('Tokyo', 'JP'),
    'KIX': ('Osaka', 'JP'),
    'ITM': ('Osaka', 'JP'),
    'NGO': ('Nagoya', 'JP'),
    'CTS': ('Sapporo', 'JP'),
    'FUK': ('Fukuoka', 'JP'),
    'OKA': ('Okinawa', 'JP'),
    'KOJ': ('Kagoshima', 'JP'),
    'HIJ': ('Hiroshima', 'JP'),
    'SDJ': ('Sendai', 'JP'),
    'KMJ': ('Kumamoto', 'JP'),

    'ICN': ('Seoul', 'KR'),
    'GMP': ('Seoul', 'KR'),
    'PUS': ('Busan', 'KR'),
    'CJU': ('Jeju', 'KR'),
    'TAE': ('Daegu', 'KR'),

    'ULN': ('Ulaanbaatar', 'MN'),

    'SIN': ('Singapore', 'SG'),
    'KUL': ('Kuala Lumpur', 'MY'),
    'PEN': ('Penang', 'MY'),
    'BKI': ('Kota Kinabalu', 'MY'),
    'KCH': ('Kuching', 'MY'),
    'LGK': ('Langkawi', 'MY'),

    'BKK': ('Bangkok', 'TH'),
    'DMK': ('Bangkok', 'TH'),
    'HKT': ('Phuket', 'TH'),
    'CNX': ('Chiang Mai', 'TH'),
    'USM': ('Koh Samui', 'TH'),
    'KBV': ('Krabi', 'TH'),

    'CGK': ('Jakarta', 'ID'),
    'DPS': ('Bali', 'ID'),
    'SUB': ('Surabaya', 'ID'),
    'UPG': ('Makassar', 'ID'),
    'MDC': ('Manado', 'ID'),
    'JOG': ('Yogyakarta', 'ID'),
    'BPN': ('Balikpapan', 'ID'),

    'MNL': ('Manila', 'PH'),
    'CEB': ('Cebu', 'PH'),
    'DVO': ('Davao', 'PH'),
    'CRK': ('Clark', 'PH'),

    'SGN': ('Ho Chi Minh City', 'VN'),
    'HAN': ('Hanoi', 'VN'),
    'DAD': ('Da Nang', 'VN'),
    'CXR': ('Nha Trang', 'VN'),
    'PQC': ('Phu Quoc', 'VN'),

    'PNH': ('Phnom Penh', 'KH'),
    'REP': ('Siem Reap', 'KH'),
    'VTE': ('Vientiane', 'LA'),
    'RGN': ('Yangon', 'MM'),
    'MDL': ('Mandalay', 'MM'),
    'BWN': ('Bandar Seri Begawan', 'BN'),

    'SYD': ('Sydney', 'AU'),
    'MEL': ('Melbourne', 'AU'),
    'BNE': ('Brisbane', 'AU'),
    'PER': ('Perth', 'AU'),
    'ADL': ('Adelaide', 'AU'),
    'OOL': ('Gold Coast', 'AU'),
    'CBR': ('Canberra', 'AU'),
    'CNS': ('Cairns', 'AU'),
    'HBA': ('Hobart', 'AU'),
    'DRW': ('Darwin', 'AU'),
    'TSV': ('Townsville', 'AU'),

    'AKL': ('Auckland', 'NZ'),
    'WLG': ('Wellington', 'NZ'),
    'CHC': ('Christchurch', 'NZ'),
    'ZQN': ('Queenstown', 'NZ'),
    'DUD': ('Dunedin', 'NZ'),

    'NAN': ('Nadi', 'FJ'),
    'PPT': ('Papeete', 'PF'),
    'NOU': ('Noumea', 'NC'),
    'APW': ('Apia', 'WS'),

    'MEX': ('Mexico City', 'MX'),
    'CUN': ('Cancun', 'MX'),
    'GDL': ('Guadalajara', 'MX'),
    'MTY': ('Monterrey', 'MX'),
    'TIJ': ('Tijuana', 'MX'),
    'SJD': ('San Jose del Cabo', 'MX'),
    'PVR': ('Puerto Vallarta', 'MX'),
    'MID': ('Merida', 'MX'),
    'CUL': ('Culiacan', 'MX'),
    'HMO': ('Hermosillo', 'MX'),
    'BJX': ('Leon', 'MX'),
    'QRO': ('Queretaro', 'MX'),
    'CME': ('Ciudad del Carmen', 'MX'),

    'GRU': ('Sao Paulo', 'BR'),
    'CGH': ('Sao Paulo', 'BR'),
    'GIG': ('Rio de Janeiro', 'BR'),
    'SDU': ('Rio de Janeiro', 'BR'),
    'BSB': ('Brasilia', 'BR'),
    'CNF': ('Belo Horizonte', 'BR'),
    'SSA': ('Salvador', 'BR'),
    'REC': ('Recife', 'BR'),
    'FOR': ('Fortaleza', 'BR'),
    'CWB': ('Curitiba', 'BR'),
    'POA': ('Porto Alegre', 'BR'),
    'FLN': ('Florianopolis', 'BR'),
    'BEL': ('Belem', 'BR'),
    'MAO': ('Manaus', 'BR'),
    'VCP': ('Campinas', 'BR'),
    'NAT': ('Natal', 'BR'),
    'MCZ': ('Maceio', 'BR'),
    'GYN': ('Goiania', 'BR'),

    'EZE': ('Buenos Aires', 'AR'),
    'AEP': ('Buenos Aires', 'AR'),
    'COR': ('Cordoba', 'AR'),
    'MDZ': ('Mendoza', 'AR'),
    'ROS': ('Rosario', 'AR'),
    'BRC': ('Bariloche', 'AR'),
    'IGR': ('Iguazu', 'AR'),
    'USH': ('Ushuaia', 'AR'),

    'SCL': ('Santiago', 'CL'),
    'CCP': ('Concepcion', 'CL'),
    'IQQ': ('Iquique', 'CL'),
    'PMC': ('Puerto Montt', 'CL'),
    'PUQ': ('Punta Arenas', 'CL'),

    'LIM': ('Lima', 'PE'),
    'CUZ': ('Cusco', 'PE'),
    'AQP': ('Arequipa', 'PE'),

    'BOG': ('Bogota', 'CO'),
    'MDE': ('Medellin', 'CO'),
    'CLO': ('Cali', 'CO'),
    'CTG': ('Cartagena', 'CO'),
    'BAQ': ('Barranquilla', 'CO'),

    'UIO': ('Quito', 'EC'),
    'GYE': ('Guayaquil', 'EC'),
    'GPS': ('Galapagos', 'EC'),

    'CCS': ('Caracas', 'VE'),
    'LPB': ('La Paz', 'BO'),
    'VVI': ('Santa Cruz', 'BO'),
    'ASU': ('Asuncion', 'PY'),
    'MVD': ('Montevideo', 'UY'),
    'GEO': ('Georgetown', 'GY'),
    'PBM': ('Paramaribo', 'SR'),

    'PTY': ('Panama City', 'PA'),
    'SJO': ('San Jose', 'CR'),
    'SAL': ('San Salvador', 'SV'),
    'GUA': ('Guatemala City', 'GT'),
    'TGU': ('Tegucigalpa', 'HN'),
    'SAP': ('San Pedro Sula', 'HN'),
    'MGA': ('Managua', 'NI'),
    'BZE': ('Belize City', 'BZ'),
    'HAV': ('Havana', 'CU'),
    'VRA': ('Varadero', 'CU'),
    'SDQ': ('Santo Domingo', 'DO'),
    'PUJ': ('Punta Cana', 'DO'),
    'SJU': ('San Juan', 'PR'),
    'KIN': ('Kingston', 'JM'),
    'MBJ': ('Montego Bay', 'JM'),
    'NAS': ('Nassau', 'BS'),
    'POS': ('Port of Spain', 'TT'),
    'BGI': ('Bridgetown', 'BB'),
    'AUA': ('Oranjestad', 'AW'),
    'CUR': ('Willemstad', 'CW'),
    'SXM': ('Philipsburg', 'SX'),
    'PTP': ('Pointe-a-Pitre', 'GP'),
    'FDF': ('Fort-de-France', 'MQ'),
}

VALID_IATA_CODES = set(IATA_TO_CITY.keys())

US_STATE_TO_ABBR = {
    'alabama': 'AL', 'alaska': 'AK', 'arizona': 'AZ', 'arkansas': 'AR',
    'california': 'CA', 'colorado': 'CO', 'connecticut': 'CT', 'delaware': 'DE',
    'florida': 'FL', 'georgia': 'GA', 'hawaii': 'HI', 'idaho': 'ID',
    'illinois': 'IL', 'indiana': 'IN', 'iowa': 'IA', 'kansas': 'KS',
    'kentucky': 'KY', 'louisiana': 'LA', 'maine': 'ME', 'maryland': 'MD',
    'massachusetts': 'MA', 'michigan': 'MI', 'minnesota': 'MN', 'mississippi': 'MS',
    'missouri': 'MO', 'montana': 'MT', 'nebraska': 'NE', 'nevada': 'NV',
    'new hampshire': 'NH', 'new jersey': 'NJ', 'new mexico': 'NM', 'new york': 'NY',
    'north carolina': 'NC', 'north dakota': 'ND', 'ohio': 'OH', 'oklahoma': 'OK',
    'oregon': 'OR', 'pennsylvania': 'PA', 'rhode island': 'RI', 'south carolina': 'SC',
    'south dakota': 'SD', 'tennessee': 'TN', 'texas': 'TX', 'utah': 'UT',
    'vermont': 'VT', 'virginia': 'VA', 'washington': 'WA', 'west virginia': 'WV',
    'wisconsin': 'WI', 'wyoming': 'WY', 'district of columbia': 'DC',
}

US_ABBR_SET = set(US_STATE_TO_ABBR.values())
